//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionarios
    {
        public Questionarios()
        {
            this.Perguntas = new HashSet<Perguntas>();
            this.Renderizar = new HashSet<Renderizar>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<bool> ativo { get; set; }
    
        public virtual ICollection<Perguntas> Perguntas { get; set; }
        public virtual ICollection<Renderizar> Renderizar { get; set; }
    }
}
