//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respostas
    {
        public Respostas()
        {
            this.Prenchimentos = new HashSet<Prenchimentos>();
        }
    
        public int id { get; set; }
        public string resposta { get; set; }
        public Nullable<int> id_pergunta { get; set; }
        public int ordem { get; set; }
    
        public virtual Perguntas Perguntas { get; set; }
        public virtual ICollection<Prenchimentos> Prenchimentos { get; set; }
    }
}
