//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perguntas
    {
        public Perguntas()
        {
            this.Respostas = new HashSet<Respostas>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public bool obrigatorio { get; set; }
        public Nullable<int> id_questionario { get; set; }
        public Nullable<int> tipo { get; set; }
        public int numero { get; set; }
    
        public virtual Questionarios Questionarios { get; set; }
        public virtual Tipos Tipos { get; set; }
        public virtual ICollection<Respostas> Respostas { get; set; }
    }
}
