//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prenchimentos
    {
        public int id { get; set; }
        public int id_renderizar { get; set; }
        public string valor_resposta { get; set; }
        public Nullable<int> id_pergunta { get; set; }
        public string usuario { get; set; }
        public Nullable<int> resposta { get; set; }
    
        public virtual Renderizar Renderizar { get; set; }
    }
}
