//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renderizar
    {
        public Renderizar()
        {
            this.Prenchimentos = new HashSet<Prenchimentos>();
        }
    
        public int id { get; set; }
        public int id_questionario { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public byte[] data_validade { get; set; }
        public System.DateTime data_renderizado { get; set; }
        public bool publico { get; set; }
    
        public virtual Questionarios Questionarios { get; set; }
        public virtual ICollection<Prenchimentos> Prenchimentos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
