//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateApi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos
    {
        public Tipos()
        {
            this.Perguntas = new HashSet<Perguntas>();
        }
    
        public int id { get; set; }
        public string desc_tipo { get; set; }
    
        public virtual ICollection<Perguntas> Perguntas { get; set; }
    }
}
